default: &default-config
  rounds: 10
  training_args: &default-training-args
    num_updates: 20
    loader_args: &default-loader-args
      batch_size: 50
silo: *default-config
federated: *default-config
mega: *default-config
fast:
  <<: *default-config
  rounds: 1
  training_args:
    <<: *default-training-args
    num_updates: 1
    loader_args:
      <<: *default-loader-args
      batch_size: 10000

